apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: more-cars-frontend
          #image: docker.io/dennisgerike/more-cars-frontend:latest
          image: ghcr.io/more-cars/frontend:latest
          volumeMounts:
            - name: cert-volume
              mountPath: /app/certificates
              readOnly: true
          env:
            - name: API_HOST
              value: $(API_SERVICE_SERVICE_HOST)
            - name: API_PORT
              value: $(API_SERVICE_SERVICE_PORT)
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: basic-auth
                  key: username
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: basic-auth
                  key: password
            - name: API_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: basic-auth
                  key: username
            - name: API_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: basic-auth
                  key: password
          resources:
            requests:
              cpu: "50m"
              memory: "210Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
      volumes:
        - name: cert-volume
          secret:
            secretName: certificate-frontend
