apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../app
  - namespace.yaml

namespace: dev

images:
  - name: docker.io/dennisgerike/more-cars-frontend
    newName: localhost/mc-frontend
    newTag: dev
